import React, { useState } from "react";
import { Transaction } from "../types";
import { analyzeSpending } from "../services/geminiService";
import { motion } from "framer-motion";
import { Sparkles, RefreshCw, AlertCircle } from "lucide-react";
import ReactMarkdown from "react-markdown";
import { ToastType } from "./ui/Toast";

interface AIAdvisorProps {
  transactions: Transaction[];
  showToast: (msg: string, type: ToastType) => void;
}

export const AIAdvisor: React.FC<AIAdvisorProps> = ({
  transactions,
  showToast,
}) => {
  const [analysis, setAnalysis] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleAnalysis = async () => {
    if (transactions.length === 0) {
      const msg = "Please add some transactions first to get an analysis.";
      setError(msg);
      showToast(msg, "error");
      return;
    }
    setLoading(true);
    setError(null);
    try {
      const result = await analyzeSpending(transactions);
      setAnalysis(result);
      showToast("Spending analysis generated!", "success");
    } catch (err) {
      const msg =
        "Failed to generate insights. Check your API key configuration.";
      setError(msg);
      showToast(msg, "error");
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <div className="text-center space-y-4">
        <div className="inline-flex items-center justify-center p-3 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-2xl shadow-lg shadow-purple-200 dark:shadow-none">
          <Sparkles className="w-8 h-8 text-white" />
        </div>
        <h2 className="text-3xl font-bold text-slate-800 dark:text-white">
          AI Financial Advisor
        </h2>
        <p className="text-slate-500 dark:text-slate-400 max-w-lg mx-auto">
          Unlock insights into your spending habits. Our AI analyzes your
          transaction history to provide personalized budgeting tips and
          identify saving opportunities.
        </p>
      </div>

      {!analysis && !loading && (
        <div className="flex justify-center mt-8">
          <button
            onClick={handleAnalysis}
            className="group relative px-8 py-4 bg-indigo-600 dark:bg-indigo-500 text-white font-bold rounded-full shadow-xl shadow-indigo-200 dark:shadow-none hover:shadow-2xl hover:bg-indigo-700 dark:hover:bg-indigo-600 transition-all transform hover:-translate-y-1"
          >
            <span className="flex items-center gap-2">
              <Sparkles className="w-5 h-5 group-hover:animate-spin" />
              Generate Insights
            </span>
          </button>
        </div>
      )}

      {loading && (
        <div className="flex flex-col items-center justify-center py-12 space-y-4">
          <div className="w-12 h-12 border-4 border-indigo-200 border-t-indigo-600 dark:border-indigo-900 dark:border-t-indigo-500 rounded-full animate-spin"></div>
          <p className="text-indigo-600 dark:text-indigo-400 font-medium animate-pulse">
            Analyzing your finances...
          </p>
        </div>
      )}

      {error && (
        <div className="flex items-center gap-3 p-4 bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-400 rounded-xl border border-red-100 dark:border-red-900/50">
          <AlertCircle className="w-5 h-5 flex-shrink-0" />
          <p>{error}</p>
        </div>
      )}

      {analysis && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white dark:bg-slate-900 p-8 rounded-3xl shadow-sm border border-slate-100 dark:border-slate-800 transition-colors"
        >
          <div className="flex justify-between items-start mb-6">
            <h3 className="text-xl font-bold m-0 text-slate-800 dark:text-white">
              Your Financial Report
            </h3>
            <button
              onClick={handleAnalysis}
              className="text-slate-400 dark:text-slate-500 hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors"
              title="Refresh Analysis"
            >
              <RefreshCw className="w-5 h-5" />
            </button>
          </div>
          <div className="bg-slate-50 dark:bg-slate-800 p-6 rounded-2xl border border-slate-100 dark:border-slate-700">
            <div className="prose prose-slate dark:prose-invert max-w-none prose-p:leading-relaxed prose-headings:font-bold prose-a:text-indigo-600 dark:prose-a:text-indigo-400">
              <ReactMarkdown>{analysis}</ReactMarkdown>
            </div>
          </div>
          <div className="mt-6 text-center">
            <p className="text-xs text-slate-400 dark:text-slate-600">
              Generated by Gemini 2.5 Flash. AI advice should not replace
              professional financial consultation.
            </p>
          </div>
        </motion.div>
      )}
    </div>
  );
};
